### PR TITLE
Error when Clojurescript is earlier than 1.10

### PR DESCRIPTION
**Pull request by alysbrooks**
If you have the wrong version of Clojurescript, you may get unclear errors upon trying to run Kaocha, so it's best to check the version upfront and warn the user.

This is the kaocha-cljs version of [ Throw error when on a version of Clojure prior to 1.9.](https://github.com/lambdaisland/kaocha/pull/177). I'm not sure this is the exactly the right approach, as I'm less familiar with this plugin. In particular, I'm wondering whether we want to error out on the Clojure side of this plugin, too.

### CODE REVIEW

**Comment by plexus** [comment]
I think we should do this on the Clojure side. If people use an incompatible version of ClojureScript, then we may never get to the point where this code is compiled and running, so the error would never show up.

Instead in the [`-load` implementation for a cljs test suite](https://github.com/lambdaisland/kaocha-cljs/blob/master/src/kaocha/type/cljs.clj#L59) we can see which clojurescript version is available, and return a testable with a load error if it's too low.

``` clojure
(defmethod ... [testable]
  (if ...cljs-version-too-low...
     (assoc testable :kaocha.testable/load-error (ex-info "ClojureScript version too low" {:expected "1.10" :got "..."})
     ...run normally...))
```

The kaocha machinery should do the rest.

**Comment by alysbrooks** [comment]
Doing it in `-load` may be too late. I keep getting a "No such var: repl/repl-options" even though, as far as I can tell, Clojurescript 1.9 had `repl-options`.

**Comment by plexus** [comment]
Looks good I think!

**Comment by plexus** [comment]
singin-dancin

**Pull request merged**
